### ISSUE TITLE
only can caculate TE of '0 1' series?

### ISSUE THREAD

**Issue by xiangruizxr** [ruteee/TransferEntropy#1]
how can I use it to caculate TE of  continuous, real values time series?

**Comment by ruteee** [comment]
it is not possible. It is used for discrete time series

**Comment by xiangruizxr** [comment]
Ok,thanks. Do you know how to calculate TE of continuous time series？

**Comment by xiangruizxr** [comment]
Ok,thanks. Do you know how to calculate TE of continuous time series？

**Comment by ruteee** [comment]
There are some papers that may help you with this. 

https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008054
https://arxiv.org/abs/1610.08192
https://scholarcommons.sc.edu/etd/5243/
